quiz_engine/urls.py
from django.conf.urls import url
from django.contrib import admin

from quizzes import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home'),
]

quizzes/models.py
from django.db import models


class Question(models.Model):
    text = models.TextField(default='')


class Answer(models.Model):
    text = models.TextField(default='')
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='answer',
    )

quizzes/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Question, Answer


def home_page(request):
    result = ''
    question_number = 1
    if request.method == 'POST':
        answer = request.POST.get('answer', False)
        question_number += request.POST.get('question_number', 1)
        if (answer == "John"):
            result = 'Correct!'
        else:
            result = 'Wrong!'

    question = Question.objects.get(pk=question_number)

    answers = Answer.objects.filter(question=question)

    answer_texts = []

    for a in answers:
        answer_texts.append(a.text)

    return render(
        request,
        'home.html',
        {
            'result': result,
            'question_number': question_number,
            'question_text': question.text,
            'answers': answer_texts
        }
    )

quizzes/templates/home.html
<html>
    <head>
        <title>Quiz Time!</title>
    </head>
    <body>
        <h1>Quiz Time!</h1>
        <div id="id_result">
            <div class="result_text">{{ result }}</div>
        </div>
        <form id="id_question" method="POST">
            <div class="question_number">Question Number: {{ question_number }}</div>
            <div class="question_text">{{ question_text }}</div>
            {% for answer in answers %}
            <input type="radio" class="answer" name="answer" value={{answer}}>{{answer}}<br>
            {% endfor %}
            <input type="submit" class="submit">

            {% csrf_token %}
        </form>
    </body>
</html>